#!/bin/bash

# TW4 Persistent Display Setup Script
# Author: Ned Bollard
# Description: Override GNOME display management and set persistent configuration

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo -e "${BLUE}================================${NC}"
    echo -e "${CYAN}TW4 Persistent Display Setup${NC}"
    echo -e "${BLUE}================================${NC}"
}

# Stop GNOME display management services
stop_gnome_display() {
    print_status "Stopping GNOME display management..."
    
    # Stop GNOME display management services
    systemctl --user stop gnome-shell-display-manager 2>/dev/null
    gsettings set org.gnome.settings-daemon.plugins.xsettings active false 2>/dev/null
    
    # Kill any running display configuration daemons
    pkill -f "gnome-settings-daemon" 2>/dev/null
    pkill -f "gnome-shell" 2>/dev/null
    
    sleep 2
    print_status "✅ GNOME display management stopped"
}

# Create persistent xorg configuration
create_xorg_config() {
    print_status "Creating persistent X11 configuration..."
    
    # Create .xprofile directory if it doesn't exist
    mkdir -p ~/.config
    mkdir -p ~/.config/xorg.conf.d
    
    # Create display configuration file
    cat > ~/.config/xorg.conf.d/99-kensington-dock.conf << 'EOF'
# Kensington Dock Display Configuration
# Auto-generated by TW4 display setup

Section "Monitor"
    Identifier "eDP-1"
    Option "Primary" "true"
    Option "Enable" "true"
EndSection

Section "Monitor"
    Identifier "DP-3"
    Option "Enable" "true"
    Option "RightOf" "eDP-1"
EndSection

Section "Monitor"
    Identifier "DP-4"
    Option "Enable" "true"
    Option "RightOf" "DP-3"
EndSection

Section "ServerLayout"
    Identifier "Layout0"
    Screen 0 "Screen0"
    InputDevice "Keyboard0" "Keyboard0"
    Option "Xinerama" "1"
EndSection
EOF

    # Create startup script
    cat > ~/.config/autostart/kensington-display-setup << 'EOF'
#!/bin/bash
# Kensington Dock Display Setup
# Auto-start display configuration for TW4

sleep 5
xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal --primary
xrandr --output DP-3 --mode 1920x1080 --pos 1920x0 --rotate normal
xrandr --output DP-4 --mode 1920x1080 --pos 3840x0 --rotate normal

# Notify user
notify-send "TW4 Display Setup" "Kensington dock configuration applied" 2>/dev/null || true
EOF

    chmod +x ~/.config/autostart/kensington-display-setup
    
    # Update .xprofile to run setup on login
    if ! grep -q "kensington-display-setup" ~/.xprofile; then
        echo "" >> ~/.xprofile
        echo "# Kensington Dock Display Setup" >> ~/.xprofile
        echo "if [ -x ~/.config/autostart/kensington-display-setup ]; then" >> ~/.xprofile
        echo "    ~/.config/autostart/kensington-display-setup" >> ~/.xprofile
        echo "fi" >> ~/.xprofile
    fi
    
    print_status "✅ Persistent configuration created"
}

# Apply display configuration immediately
apply_config() {
    print_status "Applying display configuration..."
    
    # Apply xrandr settings directly
    xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal --primary
    sleep 1
    xrandr --output DP-3 --mode 1920x1080 --pos 1920x0 --rotate normal
    sleep 1
    xrandr --output DP-4 --mode 1920x1080 --pos 3840x0 --rotate normal
    
    print_status "✅ Display configuration applied"
}

# Disable GNOME auto-configuration
disable_gnome_autoconfig() {
    print_status "Disabling GNOME auto-configuration..."
    
    # Disable GNOME's automatic display configuration
    gsettings set org.gnome.mutter experimental-features "disable-x11-autorotation" true 2>/dev/null
    gsettings set org.gnome.mutter experimental-features "scale-monitor-framebuffer" false 2>/dev/null
    gsettings set org.gnome.desktop.interface "scaling-factor" 1 2>/dev/null
    
    print_status "✅ GNOME auto-configuration disabled"
}

# Show current status
show_status() {
    print_header
    echo -e "${PURPLE}Current Display Status:${NC}"
    echo ""
    
    # Show xrandr current state
    xrandr --current
    echo ""
    
    # Show GNOME settings
    echo -e "${CYAN}GNOME Display Settings:${NC}"
    gsettings get org.gnome.mutter experimental-features 2>/dev/null || echo "Not available"
    echo ""
    
    # Show if configuration files exist
    echo -e "${CYAN}Configuration Files:${NC}"
    if [ -f ~/.config/xorg.conf.d/99-kensington-dock.conf ]; then
        echo -e "${GREEN}✅ X11 config: ~/.config/xorg.conf.d/99-kensington-dock.conf${NC}"
    else
        echo -e "${RED}❌ X11 config: Not found${NC}"
    fi
    
    if [ -f ~/.config/autostart/kensington-display-setup ]; then
        echo -e "${GREEN}✅ Autostart: ~/.config/autostart/kensington-display-setup${NC}"
    else
        echo -e "${RED}❌ Autostart: Not found${NC}"
    fi
    echo ""
}

# Show help menu
show_help() {
    print_header
    echo -e "${PURPLE}Persistent Display Commands:${NC}"
    echo -e "${GREEN}  stop-gnome${NC}    - Stop GNOME display management"
    echo -e "${GREEN}  create-config${NC}  - Create persistent configuration"
    echo -e "${GREEN}  apply${NC}        - Apply display configuration"
    echo -e "${GREEN}  disable-auto${NC}  - Disable GNOME auto-configuration"
    echo -e "${GREEN}  status${NC}       - Show current status"
    echo -e "${GREEN}  help${NC}         - Show this help menu"
    echo ""
    echo -e "${YELLOW}Note: This script bypasses GNOME's display management${NC}"
    echo ""
}

# Main script logic
main() {
    case "${1:-help}" in
        "stop-gnome")
            stop_gnome_display
            ;;
        "create-config")
            create_xorg_config
            ;;
        "apply")
            apply_config
            ;;
        "disable-auto")
            disable_gnome_autoconfig
            ;;
        "status")
            show_status
            ;;
        "help"|"-h"|"--help")
            show_help
            ;;
        *)
            print_error "Unknown command: $1"
            echo ""
            show_help
            exit 1
            ;;
    esac
}

# Run main function with all arguments
main "$@"
